import type { Metadata } from "next";
import "./globals.css";
import { DarkModeProvider } from "./context/DarkModeContext";



export const metadata: Metadata = {
  title: "Net Zero Think",
  description: "Generated by create next app",
  icons:{
    icon:"/favicon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`antialiased`}>
        <DarkModeProvider>
        {children}
        </DarkModeProvider>
      </body>
    </html>
  );
}
