import type { Metadata } from "next";
import "./globals.css";
import { DarkModeProvider } from "./context/DarkModeContext";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"


export const metadata: Metadata = {
  title: "Net Zero Think",
  description: "Generated by create next app",
  icons:{
    icon:"/favicon.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DarkModeProvider>
        {children}
        <Analytics/>
        <SpeedInsights/>
        </DarkModeProvider>
      </body>
    </html>
  );
}
